// Code generated by mockery v2.10.0. DO NOT EDIT.

package citcall

import (
	context "context"

	citcall "github.com/kennykarnama/citcall-test/client/citcall"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetCountries provides a mock function with given fields: ctx
func (_m *Client) GetCountries(ctx context.Context) (citcall.Countries, error) {
	ret := _m.Called(ctx)

	var r0 citcall.Countries
	if rf, ok := ret.Get(0).(func(context.Context) citcall.Countries); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(citcall.Countries)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
